#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thirdeye.backend.fullname" . }}
  labels:
    app: {{ include "thirdeye.name" . }}
    chart: {{ include "thirdeye.chart" . }}
    component: {{ .Values.backend.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "thirdeye.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.backend.name }}
  replicas: {{ .Values.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "thirdeye.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.backend.name }}
      annotations:
{{ toYaml .Values.backend.podAnnotations | indent 8 }}
    spec:
      nodeSelector:
{{ toYaml .Values.backend.nodeSelector | indent 8 }}
      affinity:
{{ toYaml .Values.backend.affinity | indent 8 }}
      tolerations:
{{ toYaml .Values.backend.tolerations | indent 8 }}
      securityContext:
        runAsGroup: 1000
        fsGroup: 1000
        runAsUser: 1000
      containers:
      - name: backend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [
            "pinot-quickstart",
            "backend"
        ]
        ports:
          - containerPort: {{ .Values.backend.port }}
            protocol: TCP
          - containerPort: {{ .Values.backend.adminport }}
            protocol: TCP
        volumeMounts:
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/data-sources/data-sources-config.yml"
            subPath: "data-sources-config.yml"
            readOnly: true
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/data-sources/cache-config.yml"
            subPath: "cache-config.yml"
            readOnly: true
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/detector.yml"
            subPath: "detector.yml"
            readOnly: true
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/dashboard.yml"
            subPath: "dashboard.yml"
            readOnly: true
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/persistence.yml"
            subPath: "persistence.yml"
            readOnly: true
          {{- if .Values.backend.holidayLoaderKey }}
          - name: thirdeye-config
            mountPath: "/opt/thirdeye/config/pinot-quickstart/holiday-loader-key.json"
            subPath: "holiday-loader-key.json"
            readOnly: true
          {{- end }}
        resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
      restartPolicy: Always
      volumes:
        - name: thirdeye-config
          configMap:
            name: thirdeye-config
