dataSourceConfigs:
  # Default option is to run thirdeye with a pinot-quickstart cluster
  - className: org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource
    properties:
      zookeeperUrl: 'pinot-zookeeper:2181'
      clusterName: 'pinot-quickstart'
      controllerConnectionScheme: 'http'
      controllerHost: 'pinot-controller'
      controllerPort: 9000
      cacheLoaderClassName: org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
    metadataSourceConfigs:
      - className: org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource